.Dd $Mdocdate: March 8 2017 $
.Dt DDMIN 1
.Os
.Sh NAME
.Nm ddmin
.Nd minimise interesting files automatically
.Sh SYNOPSIS
.Nm ddmin
.Op Fl b 
.Op Fl h
.Ar tester
.Ar interesting
.Sh DESCRIPTION
.Nm
minimises file
.Ar interesting
in place using delta debugging.
It works by deleting lines (or bytes with -b) while ensuring
.Ar tester
returns 0 when executed.
.Sh EXIT STATUS
.Ex -std ddmin
.Sh EXAMPLE
.Bd -literal
Given the input file interesting.c:

#include <stdio.h>

int main()
{
	printf("hello world!");
	return 0;
}

The test script test.sh:

#! /bin/sh

set -e

gcc interesting.c
if ! ./a.out | grep -q "hello" then
	exit 1
fi

The invocation:

ddmin -b ./test.sh ./interesting.c

Produces the minimised output:

main(){printf("hello");return;}
.Ed
